# Use a imagem base Node.js
FROM node:14

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos de package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie todos os arquivos do aplicativo React para o contêiner
COPY . .

# Construa o aplicativo React
RUN npm run build

# Comando para iniciar o servidor de produção
CMD ["npm", "start"]
